# Generated by Django 4.1.7 on 2023-03-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_app", "0003_remove_medialist_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="release_year",
        ),
    ]
